name: Deploy Backend to AWS Lambda

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: backend
        run: npm install

      - name: Zip backend code
        run: |
          cd backend
          zip -r ../backend-lambda.zip .

      - name: Deploy to AWS Lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-north-1
          function_name: deepakbusa
          zip_file: backend-lambda.zip
          handler: server.handler   # <-- Update if needed
          runtime: nodejs18.x
